# Generated by Django 4.2.3 on 2023-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="duration",
            field=models.PositiveSmallIntegerField(verbose_name=1),
        ),
        migrations.AlterField(
            model_name="game",
            name="players",
            field=models.PositiveSmallIntegerField(verbose_name=1),
        ),
    ]
