# Generated by Django 4.2.5 on 2023-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_game_duration_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
