name: Django Test with PostgreSQL Example

on:
    workflow_call:
    workflow_dispatch:
    push:
       branches: [main]
    pull_request:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: website
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    services:
      postgres_main:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: website
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    strategy:
      matrix:
        python-version: ["3.10.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Python setup ${{matrix.python-version}}
        uses: actions/setup-python@v1
        with:
           python-version: ${{ matrix.python-version }}

      - name: Setup and start virtual environment
        run: | 
            python3 -m venv venv 
            source venv/bin/activate
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Run tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: localhost
          DB_DATABASE: website
          DB_PORT: 5432
        run: |
          python3 manage.py test